### ISSUE TITLE
Hello,I'm testing if everything is set up correctly by contributing to an existing repository 

### ISSUE THREAD

**Issue by FoivosMourellos** [anamartinovici/githubfun#150]

**Comment by anamartinovici** [comment]
Hi @FoivosMourellos 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by FoivosMourellos** [comment]
Hi Anna. I reopened this issue because I was mistaken, my txt file is not popping up in the repository. I followed all steps mentioned. However, after step 13 when I press the 'Push' button, Rstudio asks for my username and password for github. Although I enter the correct ones, I get this message:    
fatal: Authentication failed for 'https://github.com/anamartinovici/githubfun.git/'
Any ideas? Thanks!

**Comment by anamartinovici** [comment]
Hi @FoivosMourellos 

Indeed, there is no commit in the main branch linked to your account.
My guess is that the token you're using doesn't have the right permissions / scopes. When you generate a token, you need to select what that token is allowed to be used for. Otherwise, if you don't select anything, the token has no rights. 

See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token for more details. If you're using a classic personal access token you need to give it, at a minimum, `repo` scope. See point 8 in https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic. 

I suggest you generate a new token, make sure it has `repo` scope, and then try to commit and push again.

**Comment by FoivosMourellos** [comment]
Hi Ana,

Thanks for the tip, it works just fine now.

Best,
Foivos
