### ISSUE TITLE
I am going through these steps before the SIPS workshop and I want to be added as a collaborator for the githubfunrepo

### ISSUE THREAD

**Issue by jajapipopp123** [anamartinovici/githubfun#174]

**Comment by anamartinovici** [comment]
Hi @jajapipopp123 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

I assume you're going through the step-by-step instructions *after the first workshop of the ADF course* rather than *before the SIPS workshop*.

**Comment by jajapipopp123** [comment]
Hi @anamartinovici 

Yes, sorry I meant the ADF course. I have ran into an issue when I write a commit message, I press "commit", then "push", I receive this message

>>> /usr/bin/git push origin HEAD:refs/heads/main
error: cannot run rpostback-askpass: No such file or directory
fatal: could not read Username for 'https://github.com': Device not configured

Then my txt file doesnt appear anymore when trying to commit. However i see it in the "Changes" section with everybody elses comments. I check on[https://github.com/anamartinovici/githubfun] and my text file is not there. 

Do you know what I can do?

Thank you

**Comment by anamartinovici** [comment]
Hi @jajapipopp123 

This seems to be an old and common issue with RStudio and MacOS: https://github.com/STAT545-UBC/Discussion/issues/93

Follow the suggestions in the first post in that Issue: https://github.com/STAT545-UBC/Discussion/issues/93#issue-106631325 Specifically:
- in RStudio, click on the "Tools" menu and select "Shell"
- Run the following command: git push -u origin master
- it might ask you for your git username and password. Supply this information, make sure it is correct
- hopefully the push is successful, then you can close the window
- Now make some more edits to some file so that you have new content to push
- click on the "push" button in RStudio and this time the push should work

**Comment by anamartinovici** [comment]
Hi @jajapipopp123 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.

**Comment by jajapipopp123** [comment]
Hi @anamartinovici , Yes I did as I stated before but I have figured it out
