### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by atanasdobrikov** [anamartinovici/githubfun#175]
I am going through these steps before a GitHubFun workshop and that I want to be added as a collaborator for the repo.

**Comment by anamartinovici** [comment]
Hi @atanasdobrikov 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

I assume you're going through the step-by-step instructions *after the first workshop of the ADF course* rather than *before a GitHubFun workshop*. The workshop already happened.
