### ISSUE TITLE
The only thing more fun that GitHubFun is making this title 🤠

### ISSUE THREAD

**Issue by adrianrodsainz** [anamartinovici/githubfun#178]
I humbly submit my request to be considered as a collaborator for the forthcoming GitHubFun workshop. 

I kindly note that I have followed all the necessary steps as per the workshop guidelines and have created this issue to request your esteemed attention. Your gracious consideration of my request shall be highly appreciated.

Thank you for your time and consideration.

With utmost respect and admiration,
Adrian

**Comment by anamartinovici** [comment]
Hi @adrianrodsainz 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

You didn't introduce yourself, but I'm guessing that you are a student in the ADF course I'm currently teaching. Because we are interacting in our respective roles of student and teacher, the RSM Code of Conduct applies. This means that there's no need for a student to show this level of deference towards a teacher. A professional communication style is preferred - you can find more details in the RSM Code of Conduct or by google searching for "how to write professional emails for students".

**Comment by anamartinovici** [comment]
Hi @adrianrodsainz 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
