### ISSUE TITLE
I went through the steps to check if everything works well- (Student 461661 - Badr El Mehdi) 

### ISSUE THREAD

**Issue by badr2112** [anamartinovici/githubfun#182]
I went through all these steps before the GitHubFun workshop and I want to be added as a collaborator for the repo. 
Thank you,

**Comment by anamartinovici** [comment]
Hi @badr2112 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by badr2112** [comment]
Hello, 
Everything worked fine, until I tried to Push to github and I got this error.

>>> /usr/bin/git push origin HEAD:refs/heads/main
error: cannot run rpostback-askpass: No such file or directory
fatal: could not read Username for 'https://github.com': Device not configured

**Comment by anamartinovici** [comment]
Hi @badr2112 

1. You should tag the person your message is addressed to. In this case - you should tag me.
2. I assume you are using a Mac. If correct, then see https://github.com/anamartinovici/githubfun/issues/174#issuecomment-1508187365 for what you need to do. I also recommend you watch the recording of the April 18 session because I explained this in class.

**Comment by badr2112** [comment]
Hi @anamartinovici, 
I think that the problem is solved but I tried many things along the way so I hope that nothing is broken. For instance, I had to create a token because the password option was not supported. 
Thank you

**Comment by anamartinovici** [comment]
Hi @badr2112 I can see the file you've added to the repository, which means that you've successfully managed to connect `git`, `GitHub`, and `Rstudio` on your device. Congratulations! 
It is good you've created a token - password authentication is indeed no longer supported.

If all went fine, then you should close this issue. Otherwise, please reply to let me know if you have any questions or if there's something else I can help you with.

**Comment by anamartinovici** [comment]
Hi @badr2112 

I see you have committed to the repository. Did you experience difficulties committing to the repository? If "Yes", then reply and let me know what does difficulties are. If "No", then please close this issue.
