### ISSUE TITLE
Hi there, add me as a colaborator to the repository, thank you!

### ISSUE THREAD

**Issue by TudorOrosz** [anamartinovici/githubfun#197]
.

**Comment by anamartinovici** [comment]
Hi @TudorOrosz 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by TudorOrosz** [comment]
Hi, thank you for the invite.

Unfortunately, I still get an error in R when trying to Push, do you have any idea how I can solve it? 

![WhatsApp Image 2023-04-18 at 19 35 08](https://user-images.githubusercontent.com/130753273/232859090-34e6a1c0-0aba-4bd9-a686-9e1b731f903a.jpeg)

Thanks you!

**Comment by anamartinovici** [comment]
Hi @TudorOrosz 

See https://github.com/anamartinovici/githubfun/issues/174#issuecomment-1508187365 for what you need to do. I also recommend you watch the recording of today's session because I explained this in class.

**Comment by TudorOrosz** [comment]
Hi @anamartinovici 

I tried the solution that you suggested and I still stumble upon something I don't know how to proceed with. After I insert my username, I am not allowed to insert the password for some reason, it shows me this 'key' symbol and when I click enter it does not work, any ideas how to fix this as well?

<img width="590" alt="Screenshot 2023-04-19 at 13 02 48" src="https://user-images.githubusercontent.com/130753273/233055469-6253612c-a04c-47c0-9f41-54279ca972a6.png">

<img width="584" alt="Screenshot 2023-04-19 at 13 03 29" src="https://user-images.githubusercontent.com/130753273/233055605-2f29c7fe-b5dc-4d66-a7de-035b3a3c5016.png">

Thank you again for your time and sorry for the inconvenience.

**Comment by anamartinovici** [comment]
Hi @TudorOrosz 

This is related to something we've discussed in class yesterday, so you should also check the recording for more info. The second screenshot includes the explanation for why it didn't work. Namely, password authentication was removed and you will need to generate a token. Check the link included in the screenshot. This will also point you to a page with instructions on how to create a personal access token (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). Go for a classic token and make sure you give it `repo` permissions. 
After you generate the token, type `git push` in the terminal. It will ask again for your username and password. Note that the password is the token. Copy-paste the token and the hit `Enter`. In the terminal, it will look as if you didn't paste anything (i.e, what you are probably referring to by saying that it just shows the key symbol) - make sure you only paste the token once before hitting enter.

Let me know if it doesn't work. Otherwise, if you can successfully push, you can close this issue.

**Comment by TudorOrosz** [comment]
Hi @anamartinovici 

I followed the steps and I think it worked, however I still have trouble when trying to push / pull.

![Screenshot 2023-04-19 at 13 49 24](https://user-images.githubusercontent.com/130753273/233065893-965ae282-d583-4c11-ab01-18a4f160dfc7.png)

If it is not too much to ask, do you maybe have time for a 5 min call where you could help me sort this out more quickly? Many thanks.

**Comment by TudorOrosz** [comment]
Managed to solve it in the end:)

**Comment by anamartinovici** [comment]
Hi @TudorOrosz . I've been in a meeting, but I'm happy to hear you solved it in the meantime. Congratulations! 🎉
