### ISSUE TITLE
I would like to be added as a collaborator

### ISSUE THREAD

**Issue by AnnaChiaraSaccani** [anamartinovici/githubfun#221]
Anna Chiara Saccani - 532801as

**Comment by anamartinovici** [comment]
Hi @AnnaChiaraSaccani 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by AnnaChiaraSaccani** [comment]
Dear Anna,

I am having issues pushing the repository. When I try R-studio shows me this error:
>>> /usr/bin/git push origin HEAD:refs/heads/main
error: cannot run rpostback-askpass: No such file or directory
fatal: could not read Username for 'https://github.com': Device not configured

I do not know why this happens because I followed all the previous steps and when I ask about my user name etc. it gives me the correct answers..

What should I do?

Thank you in advance!

Best,
Anna
________________________________
Da: Ana Martinovici ***@***.***>
Inviato: venerdì 12 maggio 2023 11:54
A: anamartinovici/githubfun ***@***.***>
Cc: Anna Chiara Saccani ***@***.***>; Mention ***@***.***>
Oggetto: Re: [anamartinovici/githubfun] I would like to be added as a collaborator (Issue #221)


Hi @AnnaChiaraSaccani<https://github.com/AnnaChiaraSaccani>

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

**Comment by anamartinovici** [comment]
Hi @AnnaChiaraSaccani I think you might be using a Mac device. If that's correct, then the solution below should work.

This is a somehow old and common issue with RStudio and MacOS. For more details: https://github.com/STAT545-UBC/Discussion/issues/93

Steps to make it work:
- in RStudio, go to Terminal (it should be next to Console)
- type `git push` and hit enter
- it will probably ask you for your username and password. The username is the same as the GitHub username. The password is not your GitHub password! The password is a token you need to set up. This link explains in more detail what you need to authenticate: https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls In brief, you need to generate a personal access token. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic for how to generate a token - I recommend going for the classic type and making sure you select at least repo as scope. After you generate the token, when you try to push for the first time, RStudio will ask for your username (this is your GitHub username) and password (this is the token, not the GitHub password).
- hopefully the push is successful and your file is added to the remote
- now make some more edits to some file so that you have new content to push
- click on the "push" button in RStudio and this time the push should work. If it works, then from now on you can use the "push" button in RStudion, you don't need to use the terminal.

**Comment by AnnaChiaraSaccani** [comment]
I tried and now it says this: To https://github.com/anamartinovici/githubfun.git
 ! [rejected]        HEAD -> main (fetch first)
error: failed to push some refs to 'https://github.com/anamartinovici/githubfun.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by anamartinovici** [comment]
@AnnaChiaraSaccani This is progress. The error is due to someone else having made a change to the repo between the moment when you've cloned it and the moment when you tried to push. 
You need to follow the instructions in the errors message and (1) git pull and then (2) git push. The pull button is right next to the push button in the RStudio Git pane.

**Comment by AnnaChiaraSaccani** [comment]
Thank you!! I'm joining now
