### ISSUE TITLE
Access as collaborator

### ISSUE THREAD

**Issue by SH-Data** [anamartinovici/GitHubFun#263]
Hi, my name is Safa Haji. I will be following the 'Analyzing Digital Footprints' elective for BAM during the spring semester, (first Workshop on 16/04/2024).

**Comment by anamartinovici** [comment]
Hi @SH-Data 

I have added you as a collaborator to this repository. You need to accept the invite and then you should be able to push to this repository. If it all works fine, please close this issue. I have assigned you as 'responsible' for this, so you get to practice the feature.

Let me know if you have questions or if you experience any problems.

**Comment by SH-Data** [comment]
Hi @anamartinovici, I was able to push a file to the repository, but I was never prompted to generate an access token, just logging in to GitHub seemed to be enough. Could this cause issues down the line? I generated an access token just in case, but so far have not filled it in anywhere. 

Thank you in advance!

**Comment by anamartinovici** [comment]
Hi @SH-Data 

Good to hear that it worked to contribute to this repo!
Also, thank you for letting me know about the token. I'm not 100% sure what happened, but it might be that your device did not store the credentials for your account. This means that next time you try to push to a repo you'll be asked to log in again - this is not a problem, just a bit annoying and not something you want to do every time you push. Let me know if this happens and we can take a look together during one of the lecture breaks to fix it.

For now, I will close this issue because the reason why it was initially opened was resolved.
